### ISSUE TITLE
Adding Support for Punajbi Font (For Gurmat Sangeet)

### ISSUE THREAD

**Issue by mbaljeetsingh** [omenad/fonts#12]
Can you add the Punjabi font? As I want to write notations in Punajbi for Gurmat Sangeet and North India music.

I can help you with the Punjabi font creation. It will be very similar to Hindi Font.

**Comment by rajadain** [comment]
Thanks for checking this project out! I don't know much about the Gurmat Sangeet tradition of writing music, can you show me some samples? Is it just the Bhatkhande style but with Punjabi characters instead of Hindi (or English)? If so the translation shouldn't be very difficult.

Still, I have very little attention to spare to this project at the moment. The source files are all here if you'd like to take a stab at it yourself and open a PR. Otherwise I may eventually get to it one day.

**Comment by mbaljeetsingh** [comment]
Yes, it is Bhatkhande style with Punjabi Characters. Can you guide me where can I start, I'll give it a try?

**Comment by rajadain** [comment]
I haven't had a chance to work on documentation properly (#1), and I apologize for that. This is a _very_ condensed version:

1. Download and install the free and open-source [FontForge](https://fontforge.github.io/)
2. Use it to open the [Bhatkhande Hindi SFD file](https://github.com/omenad/fonts/blob/master/bhatkhande/hindi/OmeBhatkhandeHindi.sfd). The UFO files exist for cross software compatibility, but SFD is the native Font Forge format.
3. Pick a Gurmukhi font to get glyphs from, and ask the designer for permission to use it. It'd be great if you can find a free and open-source Gurmukhi font that allows its glyphs being reused explicitly, but it's always a good idea to get permission.
4. Change the glyphs for `s`, `r`, `g`, `m`, `p`, `d`, `n`, `[`, `]`, `;`, `'`, `\`, which covers the seven notes and mizrab-ke-bol (see [complete list of characters](https://omenad.github.io/fonts/ome-bhatkhande-hindi/))
    * Ensure that the octave, variant, meend, and dugun / tigun / etc modifiers still fit and don't collide with the splines
    * Ensure that each character's width is 1582 to maintain compatibility with the Hindi and English versions
    * Optionally change the numerals as well
5. Save it under `/ome-bhatkhande-punjabi/` as SFD
6. Add documentation for the Punjabi font by making a copy of the [Hindi one](https://github.com/omenad/fonts/blob/master/docs/_pages/ome-bhatkhande-hindi.md)
7. Open a PR. I'll review and generate the TTFs and make a new release.

Honestly, just typing that out makes me realize that this is a serious undertaking, and if you haven't edited fonts before it may be quite the challenge. If you can do 3 above, namely picking a font and getting permission from the designer to use it, and tell me which characters to use for the seven notes and the mizrab-ke-bol, I may be able to do the rest in a month or so.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain,

I have started adding the **Gurmukhi/Punjabi** support. I'm using the **_Gurmukhi Lipi Font_**, sent the mail to the owner regarding seeking permission, Hopefully he'll give the positive reply soon.

Currently I have added the **s** and **r**
![Inkedfontforge_2019-12-27_11-44-48_LI](https://user-images.githubusercontent.com/872762/71504178-6b65d100-289e-11ea-84b0-4c0a793775a8.jpg)
Can you confirm, If I'm on the right track?
Here's the punajbi **`sfd`** file
https://github.com/mbaljeetsingh/fonts/blob/master/bhatkhande/punjabi/OmeBhatkhandePunjabi.sfd

**Comment by rajadain** [comment]
Yes that looks great! Let me know if you have any specific questions.

**Comment by mbaljeetsingh** [comment]
> Yes that looks great! Let me know if you have any specific questions.

Can you please confirm by looking at the sfd file if the height and width of the glyph is alright?

**Comment by mbaljeetsingh** [comment]
#17 Added Punjabi font support, please have a look.

**Comment by mbaljeetsingh** [comment]
Hi @rajadain 

Can you please share when you'll be able to merge the font?

**Comment by rajadain** [comment]
Thanks for prodding Baljeet. Things have been crazy here with the Coronavirus, but I'll get to this soon.

Can you share more about how you're going to use this? Hopefully the TTFs unblocked you for that project. Of course we do want an official release soon as well.

**Comment by mbaljeetsingh** [comment]
Yes, I can understand the situation regarding Covid-19.

I'm actually planning to build a web/mobile app for writing notations and the we can view the notation in english, hindi and punjabi. I did test locally with hindi/english. 

Looking forward to the official release. Thanks.

**Comment by rajadain** [comment]
That's so cool! Looking forward to it!

Sounds like you may need some sort of webfont support for that as well. I've just realized that we don't do webfont generation by default in this repo, and have been using an older version of the webfonts for the docs. I'll consider adding webfont generation, but may more likely do it by hand one time and switch to using that.

In the interim, I've been doing some general cleanup [here](https://github.com/omenad/fonts/tree/font/bhatkhande-punjabi-cleanup). Will merge that in shortly.

**Comment by rajadain** [comment]
Created #19 for adding Webfonts for the docs site.

**Comment by mbaljeetsingh** [comment]
Glad to see it merged. Looking forward to using it inside my web app. Thanks

**Comment by rajadain** [comment]
Yes, thank you for all your hard work on this, and your patience. The docs have been updated as well, and you can see the new details for web apps here: https://omenad.github.io/fonts/usage/#web.

Please let me know in new issues if there's any questions. And please let me know about your app when it's done!

**Comment by rajadain** [comment]
And of course I discover a bug upon release: #24. Please wait for the next release before downloading for personal use. The webfonts will be updated automatically, so you can continue to use those.

**Comment by rajadain** [comment]
Okay, [2.2.1](https://github.com/omenad/fonts/releases/tag/2.2.1) is now out. This is good to go!
