### ISSUE TITLE
How do we use these fonts in an Android app?

### ISSUE THREAD

**Issue by inder123** [omenad/fonts#15]
Would be great if you can share instructions on how to do so. And also clarify that the license permits its use in apps. Thank you.

**Comment by rajadain** [comment]
Hello Inder,

Thank you for your interest in this project! Embedding in apps is something I had not thought about, so this was a very good question. I've added some instruction here: https://omenad.github.io/fonts/usage/#apps. Essentially, the license allows embedding in apps, as long as you credit me or Omenad either in the app or in the store description page.

I am not an expert in Android development, but searching the web I've found this official documentation: https://developer.android.com/guide/topics/resources/font-resource and this friendly video introduction: https://youtu.be/TfB-TsLFJdM.

Please tell me more about the app you're developing. I'm curious, and would love to know more.
