### ISSUE TITLE
Sa (first note) bhatkhande notation has missing sign

### ISSUE THREAD

**Issue by rckahale** [omenad/fonts#30]
First of all, wonderful library....Plenty of complex representations. 

1. I have found the first letter is incorrectly represented in Hindi version of font
It is right now shown as **स**  written by letter (s)

  Whereas it should be shown as **सा**  

  The starting note is important, so there is a need for its valid depiction.

  To keep the font backward compatible may be you can assign "saa" typing or some other unique letters for this newer representation without affecting past codes.

  Do, tell me if there is already a feature to write it the way I am expecting. 

2. On a lesser priority, it will be great if english font file also supports the two letter presentation for names of all notes. 

  Right now its just 

  S R G M P D N S

  What I would like to see is 
  Sa Re Ga Ma Pa Dha Ni Sa  (like mentioned in documentation) keeping all other addons intact

  I understand it is more volume of work to fit in 2 or even 3 (Dha) letters in place of one, so just a wish.

**Comment by rajadain** [comment]
Hi @rckahale, thanks for your note.

We used the original edition of Tantri Nad by Dr. Lalmani Misra as the guide for the font's design:

![2020-06-17](https://user-images.githubusercontent.com/1430060/85927060-a0fd6e00-b871-11ea-9f22-2fb4160108c4.jpg)

If we go off pronunciation, we cannot have सा without also having गा, मा, पा, and धा. Ultimately, they are symbols for notes, not literal Hindi.

The English variant was developed later, and was designed to be a drop-in replacement for the Hindi variant, thus it had to fit in the same space. This was one reason to not have two-letter representations. But ultimately, they are all symbols that represent notes, not words.

I hope this explanation is satisfactory.
