### ISSUE TITLE
Issue in the underscore of komal swars, in hindi font

### ISSUE THREAD

**Issue by rckahale** [omenad/fonts#31]
Applying this in Android

**Some cases there is faint blue line**

![Faint-blue-screenshot](https://user-images.githubusercontent.com/340708/88036428-2ae2e300-cb61-11ea-8762-25a4f5b4f0cd.png)
![Faint-blue-line](https://user-images.githubusercontent.com/340708/88036440-2dddd380-cb61-11ea-8a47-7608d07b3c1c.PNG)

**If i apply a margin bottom of higher value, the underscore does not shift or is visible.**

![Not-visible-underscore-screenshot](https://user-images.githubusercontent.com/340708/88036483-3cc48600-cb61-11ea-8ad5-c2ff37c64c05.PNG)
![Not-visible-underscore](https://user-images.githubusercontent.com/340708/88036472-37ffd200-cb61-11ea-9151-439454861dc9.PNG)

_If I remove the line separator_ (which is of 1dp height, applied in form of margin bottom) for the list items, the problem disappears and font is rendered as expected. This is inside a custom spinner.
![no-separator](https://user-images.githubusercontent.com/340708/88037592-bf017a00-cb62-11ea-82b1-1af2ac5606cc.png)

I checked the layout inspector to identify if the rendering elements are causing any harm to the font. Didn't find any overlapping.

I am applying the margin bottom because there is a mismatch of centering when English & Hindi font as substituted on the same rendering textview. I am ok with that, if I can position using margins

This issue is not present in English version of font.

**Comment by rajadain** [comment]
Oh hmm thanks for reporting that! We had something similar in #24. Will take a look soon.

**Comment by rajadain** [comment]
The komal swars are supposed ot have a thick underline though. With the proper text height they seem to be looking right, as in the final image. And this is not happening with the English variant?

**Comment by rckahale** [comment]
Yes. Same code if I change font to English, that works.

**Comment by rajadain** [comment]
Unfortunately I don't have access to an Android development environment, so am unable to fix this. I'll keep this issue open though.

**Comment by rckahale** [comment]
I got the fix for this. 
**`android:includeFontPadding="false"`**
had to be applied to the textviews.

Learning Android, so couldn't get cause of issue initially.

**Comment by rajadain** [comment]
Ah, thank you for reporting back the fix! Best wishes for your project! Please do share with us when it is ready.

**Comment by rckahale** [comment]
Its ready :) 


 [7SurVeer.com](https://7SurVeer.com)
 
 OR 
  
https://play.google.com/store/apps/details?id=com.greyscaleapps.saatsurveer


With Credits to you :) :) 
![omenad](https://user-images.githubusercontent.com/340708/111036875-88f16d00-8447-11eb-8046-4c461d8c1902.png)

**Comment by rajadain** [comment]
That looks awesome! 👏 👏 👏 Thanks so much for sharing!
