### ISSUE TITLE
Paluskar notation support

### ISSUE THREAD

**Issue by joshiswarali** [omenad/fonts#32]
Hey! I was wondering if you are also working on a font to support the Paluskar notation too? I think it would be pretty cool to be able to switch between the Bhatkhande and Paluskar notation styles seamlessly.

**Comment by rajadain** [comment]
Thanks for the interest. There are currently no plans to support Paluskar notation. Consider checking out [Ome Swarlipi](https://omenad.github.io/fonts/ome-swarlipi/), which takes a number of ideas from both Paluskar and Bhatkhande notation systems.

Even if a Paluskar font existed, you couldn't switch between the styles without translating the text as well. Thus, it would be a textual, not a presentational, translation.
