### ISSUE TITLE
Needed Punjabi Regular font to write the Gurbani Shabad in Gurmukhi below Sawar Notation

### ISSUE THREAD

**Issue by harminder31011973** [omenad/fonts#58]
Need Punjabi regular font to write the Gurbani Text below swar Notation

**Comment by rajadain** [comment]
Any recommendations, @mbaljeetsingh ?

**Comment by mbaljeetsingh** [comment]
Hi @harminder31011973 

I don't think this is a font's problem. You can use any Gurmukhi font. What matters I think is how you add it in the frontend. Should be straightforward if you're doing it manually. 

If you're using HTML, you can have two different divisions one below the other. One with the Shabad notation font class and one with the Gurumuki font class. Then you can just type.

Maybe you can try a font from the following website:
https://gurmukhifonts.com/

Let me know if you face any issues. Thanks :)

**Comment by rajadain** [comment]
Closing this as it has been answered above.
